/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.13.0+p3-g40b6564e
 *
 * Project: 'flasher.release+DevKit-E8-HP' 
 * Target:  'release+DevKit-E8-HP' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* AlifSemiconductor::RTOS&ThreadX:Kernel:Core@6.4.2 */
// enabling global pre include
        #define TX_SINGLE_MODE_SECURE


#endif /* PRE_INCLUDE_GLOBAL_H */
