/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.12.0+p48-gd3223e31
 *
 * Project: 'flasher.release+DevKit-E7-HE' 
 * Target:  'release+DevKit-E7-HE' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* AlifSemiconductor::RTOS&ThreadX:Kernel:Core@6.4.2 */
// enabling global pre include
        #define TX_SINGLE_MODE_SECURE


#endif /* PRE_INCLUDE_GLOBAL_H */
