/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.10.0
 *
 * Project: 'flasher.debug+E1C-HE' 
 * Target:  'debug+E1C-HE' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* AlifSemiconductor::RTOS&ThreadX:Kernel:Core@6.4.2 */
// enabling global pre include
        #define TX_SINGLE_MODE_SECURE


#endif /* PRE_INCLUDE_GLOBAL_H */
