/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.10.0
 *
 * Project: 'flasher.debug+E1C-HEA' 
 * Target:  'debug+E1C-HEA' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "alif.h"

/* ARM::CMSIS-Compiler:STDOUT:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
#define RTE_CMSIS_Compiler_STDOUT_Custom         /* CMSIS-Compiler STDOUT: Custom */
/* AlifSemiconductor::BSP:External peripherals:OSPI Flash ISSI@2.0.0 */
#define RTE_Drivers_ISSI_FLASH
/* AlifSemiconductor::CMSIS Driver:USART@2.0.0 */
#define RTE_Drivers_USART               /* Driver UART  */
/* AlifSemiconductor::Device:SOC Peripherals:GPIO@2.0.0 */
#define RTE_Drivers_IO              /* Driver GPIO */
/* AlifSemiconductor::Device:SOC Peripherals:OSPI@2.0.0 */
#define RTE_Drivers_OSPI              /* Driver OSPI */
/* AlifSemiconductor::Device:SOC Peripherals:PINCONF@2.0.0 */
#define RTE_Drivers_LL_PINCONF              /* Driver PinPAD and PinMux */
/* AlifSemiconductor::Device:SOC Peripherals:SDMMC@2.0.0 */
#define RTE_Drivers_SD              /* Driver SD */


#endif /* RTE_COMPONENTS_H */
